name: BTC_APP_CONSULTA

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'  # Executa a cada 5 minutos
  workflow_dispatch:  # Permite disparar manualmente se necessário

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout do código do repositório
      - name: Check out the repository
        uses: actions/checkout@v3

      # Configurar o Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      
      # Instalar dependências (pandas e yfinance)
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      # Rodar o script
      - name: Run BTC script
        run: |
          python app.py
      
      # Adicionar e fazer commit das mudanças
      - name: Commit and push changes
        run: |
          git config --local user.email "gersonmachado.mib@gmail.com"
          git config --local user.name "gersonmachado"
          git add data.csv
          git commit -m "Atualizando data.csv com novo valor BTC" || echo "Nenhuma alteração para commit"
          git push